name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version your app requires

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to VPS via SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@82.112.231.185 << 'EOF'
          cd /root/teeth-whitening-landing-page
          git pull origin master
          npm install --production
          npm run build
          pm2 restart my-nextjs-app
          EOF
